from dataclasses import dataclass


@dataclass(slots=True)
class Finding:
    """
    Represents a security finding generated by an analyzer.
    """

    severity: str
    title: str
    description: str
    recommendation: str

    def to_dict(self) -> dict:
        return {
            "severity": self.severity,
            "title": self.title,
            "description": self.description,
            "recommendation": self.recommendation,
        }